spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz_app?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: Rp7TEh6aj2Mqtfh9JeIXZ3e9bQXQ85
  expiration: 3600000